### PR TITLE
Add cli for llc data extraction

### PR DESCRIPTION
**Pull request by dhruvbalwada**
In response to #3 , I have put a script in python_cli_data_export called llc_extract.py. This is able to take some input options and generate a netcdf file in return.

### CODE REVIEW

**Comment by dhruvbalwada** [comment]
@Marioherreroglez  - adding Mario because he was interested.

**Comment by dhruvbalwada** [comment]
A working example. 
Screen Shot 2022-09-20 at 3 26 06 PM

To run this first singularity needs to be opened up with bindings to very specific directories. 


Screen Shot 2022-09-20 at 3 28 32 PM

**Comment by cspencerjones** [comment]
@rabernat can you merge this please? That will make it easier for me to use it

**Comment by rabernat** [comment]
Even better...I have made all of @ocean-transport/swot-st admins on this project. So you should be able to merge it yourself! 🚀

**Pull request merged**
