### PR TITLE
Small area

### PR DESCRIPTION
**Pull request by cspencerjones**
This code is useful for slicing out a small area of the data on Pleiades. The defaults are for the agulhas region from the Jones et al. Lagrangian filtering preprint. I decided to put it on a new branch since it is still in development.

### CODE REVIEW

**Comment by rsaim** [comment]
@cspencerjones - can we merge this to master?

**Comment by cspencerjones** [comment]
To be clear, you want to merge to master, not just to the `small-area` branch? We can do that if you want. It's not super clean code (which is why I have kept it on a branch) but the original isn't either I suppose.

**Comment by rsaim** [comment]
> To be clear, you want to merge to master, not just to the small-area branch? 

I was confused about which version of the scripts to work with - master, [ocean-transport:small-area](https://github.com/ocean-transport/pleiades_llc_recipes/tree/small-area), or your forked branch [cspencerjones:small-area](https://github.com/cspencerjones/pleiades_llc_recipes/tree/small-area). 

I suggested merging it to master as the version in master branch is considered the usable/latest one.

> It's not super clean code (which is why I have kept it on a branch) but the original isn't either I suppose.

I can help with cleaning this up if you could list all the improvements we need to make.

**Comment by cspencerjones** [comment]
This is now in #6

**Pull request closed without merging**
